// Generated by LiveScript 1.4.0
(function(){
  var h, _, Backbone, nssocketClient, reconnecto, queryProtocol, core, ref$, v, ValidatedModel;
  h = require('helpers');
  _ = require('underscore');
  Backbone = require('backbone4000');
  nssocketClient = require('lweb3/transports/client/nssocket').nssocketClient;
  reconnecto = require('lweb3/transports/reconnecto').reconnecto;
  queryProtocol = require('lweb3/protocols/query');
  core = require('lweb3/core').core;
  ref$ = require('validator2-extras'), v = ref$.v, ValidatedModel = ref$.ValidatedModel;
  exports.idsclient = core.extend4000({
    defaults: {
      name: 'idsclient'
    },
    initialize: function(){
      this.log('init', {}, 'init');
      return this.connection = new reconnecto({
        logger: this.logger,
        defaultChannelClass: nssocketClient.extend4000({
          defaults: {
            host: this.get('host'),
            port: this.get('port')
          }
        })
      });
    },
    send: function(msg){
      return this.connection.send(msg);
    }
  });
}).call(this);
